inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - "spec/**/*"
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

LineLength:
  Max: 100

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false  

Metrics/AbcSize:
  Max: 25
